#!/usr/bin/env python3
""" Encode video file(s) recursively to HEVC 10Bit video. """

import os
import argparse

__author__     = "Madhusudhan D Desai"
__copyright__  = "Copyright 2020, mddnix"
__license__    = "GPL"
__version__    = "1.0"
__maintainer__ = "Madhusudhan D Desai"
__email__      = "mddnix@gmail.com"
__status__     = "Production"

# Valid extensions
EXTN = ('.avi', '.flv', '.mkv', '.mov', '.mp4', 
        '.mpeg', '.mpg', '.webm', '.wmv')

PWD = os.getcwd()


# Get video files recursively in a directory with certain extensions and 
# store it in a list.
# @param Path where the script should run.
# @return List of all video files.
def get_files(path):

    video_files = []

    # Add files recursively with extension listed in EXTN tuple 
    # to 'video_files' list.
    for dirpath, dirname, filename in os.walk(path):
        for file in filename:
            for ext in EXTN:
                if file.lower().endswith(ext.lower()):
                    video_files.append(os.path.join(dirpath, file))

    # return sorted list
    return sorted(video_files)

def main():
    help_msg = 'Encode video file(s) recursively to HEVC 10Bit.'
    parser = argparse.ArgumentParser(description=help_msg)
    group = parser.add_mutually_exclusive_group()
    parser.add_argument('path', nargs='?', default=PWD, metavar='PATH', type=str, help='Path to a folder. Default is current folder.')
    group.add_argument('-a', '--all', action='store_true', help='List all videos.')
    group.add_argument('-H', '--hevc', action='store_true', help='List HEVC videos only.')
    group.add_argument('-o', '--other', action='store_true', help='List other videos. Exclude HEVC videos.')
    group.add_argument('-e', '--encode', action='store_true', help='Encode video(s) recursively to HEVC 10bit.')
    args = parser.parse_args()
    
    if args.all:
        files = get_files(args.path)
        for i in files:
            print(i)
    else:
        print("Nooooo argument")
    

if __name__ == '__main__':
    main()
